FileUploadInMVC/Models/ErrorViewModel.cs
namespace FileUploadInMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FileUploadInMVC/Models/FileModel.cs
namespace FileUploadInMVC.Models
{
    public class FileModel
    {
        public byte[] fileContent { get; set; }
        public string fileName { get; set; }    
        public IFormFile file { get; set; }

    }
}

FileUploadInMVC/Models/SelectFilesModel.cs
namespace FileUploadInMVC.Models
{
    public class SelectFilesModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Byte[] Image { get; set; }
    }
}

FileUploadInMVC/Controllers/FileUploadController.cs
using FileUploadInMVC.Models;
using Microsoft.AspNetCore.Mvc;
namespace FileUploadInMVC.Controllers {
    public class FileUploadController : Controller
    {
        private readonly MSSQLDataAccess _mSSQLDataAccess;
        private readonly FileModel _fileModel;
        public FileUploadController(MSSQLDataAccess mSSQLDataAccess, FileModel fileModel)
        {
            this._mSSQLDataAccess = mSSQLDataAccess;
            this._fileModel = fileModel;
            this._fileModel.fileContent = new byte[100000];
        }
        public IActionResult Index() { return View();}
        public async Task<IActionResult> SingleFileUploadToDatabase(IFormFile SingleFile)
        {
            using var memoryStream = new MemoryStream();
            await SingleFile.CopyToAsync(memoryStream);
            byte[] fileContent = memoryStream.ToArray();
            await _mSSQLDataAccess.SaveFileToDatabaseAsync(fileContent, SingleFile.FileName);
            _fileModel.fileContent = fileContent;
            _fileModel.fileName = SingleFile.FileName;            
            return View("Index", _fileModel);
        }
        public async Task<IActionResult> ListFiles()
        {
            var queryResult = await _mSSQLDataAccess.GetAllFilesFromDatabaseAsync();
            return View("Files",queryResult);
        }
        public async Task<IActionResult> DeleteButtonHandler(int Id)
        {
            await _mSSQLDataAccess.DeleteFileById(Id);
            var queryResult = await _mSSQLDataAccess.GetAllFilesFromDatabaseAsync();
            return View("Files", queryResult);
        }
    }
}

FileUploadInMVC/Controllers/HomeController.cs
using FileUploadInMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FileUploadInMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        public HomeController(IWebHostEnvironment environment)
        {            
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        public IActionResult SingleFileUpload(IFormFile SingleFile)
        {
            using (var fileStream = new FileStream(
                                        Path.Combine(_environment.ContentRootPath,"file.png"), 
                                        FileMode.Create, FileAccess.Write))
            {
                SingleFile.CopyTo(fileStream);                
            }
            return RedirectToAction("Index");
        }

        public IActionResult MultipleFileUpload(IEnumerable<IFormFile> MultipleFiles)
        {
            int fileCount = 1;
            foreach (var file in MultipleFiles)
            {
                using (var fileStream = new FileStream(
                                        Path.Combine($"{_environment.ContentRootPath}//Images", $"file{fileCount}.png"),
                                        FileMode.Create, FileAccess.Write))
                {
                    file.CopyTo(fileStream);
                } 
                fileCount++;
                              
            }
            return RedirectToAction("Index");
        }


        


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FileUploadInMVC/Views/FileUpload/Files.cshtml
@model IEnumerable<SelectFilesModel>
<div>

    <h4>List of uploaded files</h4>

    <table style="width:50%">
        <tr>            
            <th class="tableHead">File Name</th>
            <th class="tableHead">Image</th>
            <th class="tableHead">Action</th>
        </tr>

        @foreach (var file in @Model)
        {
            <tr>                
                <td> @file.Name </td>

                <td>
                    <img class="imageClass" src="@String.Format("data:image/gif;base64,{0}",Convert.ToBase64String(@file?.Image))"></img>
                </td>

                <td> @Html.ActionLink("Delete","DeleteButtonHandler","FileUpload",new { Id = @file.Id}) </td>

            </tr>
        }
    </table>
</div>
<style>

    .imageClass
    { 
        width:50%;
        height:50%;
    }

    .tableHead
    { 
        width:50%;
    }

    table, th, td
    {
        border: 1px solid black;
        text-align: center;
    }

</style>

FileUploadInMVC/Views/FileUpload/Index.cshtml
@model FileModel
@{
    string imgSrc;
    if(@Model?.fileContent != null) {
        var base64 = Convert.ToBase64String(@Model?.fileContent);
        imgSrc = String.Format("data:image/gif;base64,{0}", base64); }   
    else { imgSrc = String.Format("data:image/gif;base64,{0}", ""); }
}
<div>
    <h5>Single File Upload to Database</h5>
    <form method="post" asp-controller="FileUpload" asp-action="SingleFileUploadToDatabase"
          enctype="multipart/form-data">
        <input type="file" name="SingleFile" />
        <button type="submit" name="Upload">Upload</button>
    </form>
</div>
<div>
    <h5 class="divClass">Uploaded image</h5>
    <img id="imgUploaded" src="@imgSrc" class="imageClass" />
</div>
<style>
    .imageClass{
        width:50%;
        height:50%;
        padding-top:5px;
    }
    .divClass{ padding-top:15px; }
</style>

FileUploadInMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h5>Single File Upload</h5>
    <form method="post" asp-controller="Home" asp-action="SingleFileUpload"
          enctype="multipart/form-data">
        <input type="file" name="SingleFile" />
        <button type="submit" name="Upload">Upload</button>
    </form>
</div>

<br />
<br />

<div>
    <h5>Multiple File Upload</h5>
    <form method="post" asp-controller="Home" asp-action="MultipleFileUpload"
          enctype="multipart/form-data">
        <input type="file" multiple name="MultipleFiles" />
        <button type="submit" name="Upload">Upload</button>
    </form>
</div>

<br />
<br />

FileUploadInMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileUploadInMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileUploadInMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FileUploadInMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" 
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" 
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload"
                                asp-action="Index">File Upload</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload"
                                asp-action="ListFiles">Files</a>
                        </li>

                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FileUploadInMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>